# Site settings
name: Mirel&Cizek
title: Mirel&Cizek
email: mirel-cizek@cube.fr
description: "Mirel&Cizek - Rogue Taxidermy"
baseurl: ""
url: "http://cube.fr"

# Build settings
markdown: kramdown
permalinks: pretty

exclude: [LICENSE, README.md, Rakefile, c-est-humain]

# DEPRECATED
galleryDefaultSettings:
    imgDefaultExtension: .jpg
    imgDefaultThumbAppendString: -75
    imgDefaultFormats:
        500: -500
    imgAltAppendString: ' - Mirel&Cizek'

full_rebuild: true

sass:
  # loading path from site root
  # default to _sass
  sass_dir: assets/css

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      publish: true


